backend:
  name: github
  repo: TheDoubleJo/eprn
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Actualit√©s"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Image Principale", name: "image", widget: "image", required: false}
      - {label: "Date de publication", name: "date", widget: "datetime", date_format: "YYYY-MM-DD", time_format: "HH:mm:ss", format: "YYYY-MM-DD HH:mm:ss ZZ"}
      - {label: "Corps du texte", name: "body", widget: "markdown"}
